# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
