# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-11 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180911_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vote_score',
        ),
    ]
