# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-12 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180911_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
    ]
