# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='dif_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='other_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
