# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-12 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180912_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user',
            new_name='user_profile',
        ),
    ]
