# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-12 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180912_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
