# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
