# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-01 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pickup', geoposition.fields.GeopositionField(max_length=42)),
                ('dropat', geoposition.fields.GeopositionField(max_length=42)),
                ('description', models.TextField(verbose_name=b'Description of service')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('worth', models.IntegerField(default=0, verbose_name=b'worth($)')),
                ('image', models.ImageField(blank=True, default=b'default.png', upload_to=b'')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
