# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180706_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='deliver_on',
        ),
    ]
