# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180715_0418'),
    ]

    operations = [

        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name=b'Description'),
        ),
    ]
