# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180725_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deliver_on',
            field=models.TimeField(default=None, null=True),
        ),
    ]
